#
# 本目录下所有源代码的makefile，使用方法是nmake TARGET_NAME=源代码文件名字（不加后缀）
# 例如 nmake TARGET_NAME=CreateXmlFile
# Author: Wang Xuebin
# 
# Flags - 编译debug版本
#

#指定要使用的库的路径,需要用户修改的变量一般放在makefile文件的最上面
LIBXML2_HOME = D:\libxml2-2.6.30.win32
ICONV_HOME = D:\iconv-1.9.2.win32

#指定编译器选项,/c表明cl命令只编译不链接;/MTd表明使用多线程debug库;/Zi表明产生完整的调试信息;
#/Od表明关闭编译优化;/D _DEBUG表明定义一个名为_DEBUG的宏
CPP_FLAGS=/c /MTd /Zi /Od /D _DEBUG

#链接选项,/DEBUG表明创建Debug信息
EXE_LINK_FLAGS=/DEBUG

#指定链接的库
LIBS=iconv.lib libxml2.lib

#指定编译路径选项,链接路径选项
INCLUDE_FLAGS= /I $(LIBXML2_HOME)\include /I $(ICONV_HOME)\include
LIB_PATH_FLAGS = /libpath:$(ICONV_HOME)\lib /libpath:$(LIBXML2_HOME)\lib

#################################################
#
# Targets 目标
#


$(TARGET_NAME) : $(TARGET_NAME).exe

clean : $(TARGET_NAME).exe

$(TARGET_NAME).obj : $(TARGET_NAME).cpp
	cl $(CPP_FLAGS) $(INCLUDE_FLAGS) $(TARGET_NAME).cpp
	
$(TARGET_NAME).exe : $(TARGET_NAME).obj
  link $(EXE_LINK_FLAGS) $(LIB_PATH_FLAGS) $(TARGET_NAME).obj $(LIBS)
 
clean : $(TARGET_NAME).exe
  del $(TARGET_NAME).exe
  del $(TARGET_NAME).obj
  del $(TARGET_NAME).ilk
  del $(TARGET_NAME).pdb
  